# Generated by Django 5.2.5 on 2025-08-12 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Título")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                ("deadline", models.DateField(verbose_name="Prazo")),
                (
                    "finished_at",
                    models.DateField(null=True, verbose_name="Concluído em"),
                ),
            ],
        ),
    ]
