# Generated by Django 5.2.5 on 2025-08-12 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="finished_at",
            field=models.DateField(blank=True, null=True, verbose_name="Concluído em"),
        ),
    ]
